apiVersion: v1
kind: Secret
metadata:
  name: final-secret
  namespace: final-app
type: Opaque
stringData:
  MYSQL_PASSWORD: "root"
  MYSQL_ROOT_PASSWORD: "root"
  SECRET_KEY: "supersecretkey"
