apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: final-app
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2   # <-- REQUIRED FIX
  resources:
    requests:
      storage: 5Gi

